name: Generate icons
on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install llm
    - name: Create icon
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python generate-icons.py
        python generate-readme.py
    - name: Set up Git
      run: |
        git config --global user.name "Automation"
        git config --global user.email "hallo@janoelze.de"
    - name: Commit changes
      run: |
        git add .
        git commit -m "Commit message"
        git push