name: Generate icons
on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install llm
    - name: Create icon
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        bash generate-icons.sh
        bash generate-readme.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Added icons: ${timestamp}" || exit 0
        git push
